server:
  port: 8089
  forward-headers-strategy: framework
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  security:
    user:
      name: user
      password: password
    oauth2:
      authorizationserver:
        client:
          gateway:
            registration:
              client-id: "gateway-client"
              client-secret: "{noop}gateway-secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://localhost:8080/login/oauth2/code/gateway"
              post-logout-redirect-uris:
                - "http://localhost:8080/"
              scopes:
                - "openid"
                - "profile"
