server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: todo-service
          uri: lb://todo-service
          predicates:
            - Path=/todo/**
          filters:
            - RewritePath=/todo/?(?<segment>.*), /$\{segment}
