server:
  port: 8080
  forward-headers-strategy: framework
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/?(?<segment>.*), /$\{segment}
            - TokenRelay=
            - RemoveRequestHeader=Cookie
        - id: todo-service
          uri: lb://todo-service
          predicates:
            - Path=/todo/**
          filters:
            - RewritePath=/todo/?(?<segment>.*), /$\{segment}
            - TokenRelay=
            - RemoveRequestHeader=Cookie
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: spring
            client-id: gateway-client
            client-secret: "gateway-secret"
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"
            scope: openid, profile
            client-name: gateway
        provider:
          spring:
            issuer-uri: http://localhost:8089
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
